name: flutterlab
description: Flutter Lab.
version: 0.1.1+5

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
# following page: https://dart.dev/tools/pub/pubspec
flutter:
  uses-material-design: true
  # assets:
  #   - images/a_dot_burr.jpeg
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # https://flutter.dev/assets-and-images/#from-packages
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  # see https://flutter.dev/custom-fonts/#from-packages
